version: '3'
services:
  backend:
    build: .
    volumes:
      - .:/user/src/app/backend
    ports:
      - 5000:5000
    depends_on:
      - redis
    links:
      - redis
      - mongo
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /user/src/mongo
    command: mongod