version: '3'
services:
  redis:
    image: redis:4-alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo:3.7-jessie
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    command: mongod